import 'package:flutter/material.dart';
import 'package:location/location.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:med_compass/pages/getlocation.dart';

class SearchPage extends StatefulWidget {
  @override
  _SearchPageState createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
  TextEditingController _searchController = TextEditingController();
  List<String> allItems = [
    "Hospital_Name",
"Chakraborty Multi Speciality Hospital",
"Inhs Dhanvantri",
"Maricar Hospital",
"Pillar Health Centre",
"G B Pant Hospital, Port Blair",
"Care Hospital, Banjara",
"Aasha Hospitals",
"Abhaya Kidney Care Multispeciality Hospital",
"Baby Hospital",
"Dr Akbar Eye Hospital And Laser Centre",
"Dr.Ysr Memorial Hospitals",
"Hrudaya Children Hospital",
"Jeevana Jyothi Hospitals Ltd.,",
"K K Nursing Home",
"Meda Nursing Home",
"Mnr Nursing Home",
"Mythri Hospitals",
"Padmavathi Hospital",
"Pavani Multi Speciality Hospital",
"Prasanthi Nursing Home",
"Priya Multispeciality Hospital",
"Ravitej Nursing Home",
"Santhi Nursing Home",
"Sri Prakash Eye Hospital",
"Sri Sai Balaji Hospital",
"Sri Sai Kurpa Nursing Home",
"Sri Sai Venkateshwara Surgical Clinic",
"Sudhir Surgical Clinic",
"Suma Eye Clinic",
"Swetha Ent Hospital",
"Vaatsalya Hospital(Ananthapur)",
"Varun Children's Hospital",
"Venkat Sai Health Care Pvt Ltd ( Apollo Hospitals)",
"Vijaya Nursing Home",
"Divyasree Hospital",
"Mamatha Nursing Home",
"Anantapuram Praja Vaidyasala",
"Balaji Nursing Home",
"Dr B V Syamala Ratnam Hospiatal",
"Girish Multispeciality Hospital",
"Shilpa Hospital",
"Sreenivasa Nursing Home",
"Teja Nursing Home",
"Sharada Nursing Home and Falvia P Reddy Diagnostic",
"Sri Kanchani Hospital",
"Sri Veja Hospital",
"Azad Diabetic Centre",
"Devi Nursing Home",
"Spandana Hospital",
"Preethi Nursing Home",
"Babu Nursing Home - Chittoor",
"Dr. Agarwals Eye Hospital Ltd.",
"Dr. Ramalakshmi Nursing Home",
"Dr. V. K. R. Nursing Home and Scan Centre",
"Lakshmi Hospital",
"Ravi Nursing Home - Chitoor",
"S.M.Clinic",
"Sreelatha Modern Eye Hospital And Research Centre",
"Sujatha Nursing Home",
"Apollo Hospitals Aragonda",
"Balaji Hospital",
"Vijaya Nursing Home",
"Balaji Multi Speciality Hospital",
"Bhavya Child Care Center",
"Bhavyas Children Hospital",
"Chandra Mohan's Nursing Home",
"Desai Hospital",
"Desai Hospital-Madanapalli",
"Emergency Hospital",
"Gupta Nursing Home",
"Kathasagaram Hospitals",
"Leo Hospital",
"M.V.L Hospital",
"Madanapalle Hospital Pvt Ltd",
"Popular Nursing Home",
"Rama Orthopaedic Nursing Home",
"Shantharam Hospital",
"Siloam Eye Centre",
"Siloam Orthopaedic and Trauma Centre",
"Sri Kaveri Speciality Hospital",
"Usha Speciality Hospital",
"Viswa Orthopaedic Hospital",
"Saraswathi Maternity Nursing Home",
"P E S Institute Of Medical Sciences and Research",
"Rathna Childrens and General Hospital",
"Sri Priya Nursing Home",
"Apollo Multispeciality Hospital",
"Apollo Rural Hospitals",
"Asalatha Medicare Pvt Lt",
"Balaji Institute Of Surgery Research And Rehabilit",
"Balaji Orthopaedic And Trauma Hospital",
"Bhaskar Allergy and Chest Hospital",
"Clinic Nisha",
"Dbr And Sk Super Speciality Hospital",
"Eye Care Centre and Contact Lens Clinic",
"Gayatri Hospital Tirupati",
"Harshitha Hospital",
"Lotus Emergency Hosptial",
"M S Hospital",
"M.M Hospital",
"M/S Sapthagiri Eye Care Centre",
"Manohari Nursing Home",
"Meghana Hospital",
"Mother Hospital",
"Navya Netralaya Eye Hospital",
"Neelima Maternity Nursing Home",
"Nirmala Hospitals",
"Om Children Surgical Superspeciality Centre",
"Prameela Hospital",
"Prashanth Hospital",
"Purna's Remedy Hospital - Tirupathi",
"Raghavendra Urological Super Speciality Hospital (Russh Hospital)",
"Rama Nursing Home",
"Ramadevi Multi Super Speciality Hospital",
"Ramya Hospital",
"Ravi Neuro and Emergency Hospital - Chittoor",
"Sakthi Medicals",
"Shyamala Nursing Home",
"Sree Emergency and Crticial Care Hospital",
"Sri Chakra Hospitals",
"Sri Padmavathi Multi Speciality Hospital",
"Sri Ramadevi Multi Super Speciality Hospital",
"Sri Sai Ortho Care",
"Sri Sai Sudha Hospitals",
"Sri Suraksha Hospital",
"Sri Venkata Sai Hrudayalaya (The Heart Care Centre) - Tirupati",
"Sri Venkateshwara Institute Of Medical Sciences",
"Sri Venkateswara Hospitals",
"Sri Vignesh Hospital",
"Srinivasa Super Speciality Hospital",
"Suguna Nursing Home",
"Sviss Hospital",
"Swaranamrutha Hospital",
"Swarnamrutha Hospital",
"Swetha Childrens Hospital",
"Triveni Child Care Hospital",
"Vaishnavi Children Hospital",
"Vasan Healthcare Pvt Ltd",
"Venkataramana Heart And Maternity Hospital",
"Vision Care Clinic",
"Elite Hospital",
"Maha Hospitals",
"Vennela Super Speciality Eye and Dental Hospital",
"Radha Narayan Hospital For Women And Children",
"Manasa Kidney Foundation",
"Rushh Hospital",
"S V Poly Clinic",
"Sneha Super Speciality Hospital",
"Swarna E.N.T Super Speciality Hosptial",
"Swarnamurtha Hospital",
"Sri Sai Nursing Home",
"C.S.I. Hospital",
"Annapurna Hospital ( Ramarao Hospital)",
"Chaitanya Childrens Hospital",
"Eswari Nursing Home",
"Sai Kanthi Eye Hospital",
"Vani Priya Hospital",
"Abhishek Kidney and General Hospital ( Kcm Hospital)",
"Ashwini Childrens Hospital",
"Balaji Nursing Home",
"Bharathi Hospital",
"G. S. R. Heart Care Centre - Cuddapah",
"Jyothi Nursing Home",
"K.C.M. Hospital",
"Likhith Laparoscopic Centre",
"Palla Krishnaiah Memorial And Nursing Home",
"Pasupuleti Nursing Home",
"Priyatham Clinic",
"Sita Lakshmi Nursing Home",
"Siva Yogi Childrens Hospital",
"Sri Krishna Sahithi Eye Hospital",
"Srija Rainbow Childrens Hospital",
"Srinivasa Nursing Home",
"Tata Reddy Ramalinga Reddy Nursing Home",
"Thulasamma Hospital",
"Tirumala Hospitals",
"Vijaya Nursing Home",
"Vurimi Savitramma Cardiac Centre",
"Deepa Nursing Home",
"Dr G R K R Multi Speciality Hospitals",
"Jyothi Nursing Home",
"Remedy Hospital",
"Sri Satya Sai Hospital",
"Himalaya Multi Speciality Hospital",
"Usha Rani Nursing Home",
"Vishnu Nursing Home",
"Sree Durgaa Nursing Home",
"Sri Sai Nursing Home",
"Our Lady Of Fatima Hospital",
"Madhavi Nursing Home",
"Raviteja Nursing Home",
"Abhilash Netra Vidyasala",
"B. G. R. Hospital",
"Bhavya Nursing Home",
"Cnr Nursing Home",
"Dr. S. V. R. Hospital",
"Jaya Vishnu Nursing Home",
"Kalyana Chakravarthy Hospitals - Proddatur",
"Kathya Nursing Home",
"Lakshmi Kishore Hospital",
"Latha Mutispeciality Hospital - Proddatur",
"Orthopaedic And Maternity Hospital",
"Prasad Nursing Home",
"Shree Veja Nursing Home",
"Siva Nursing Home",
"Sree Veja Nursing Home",
"Sri Sai Hospitals",
"Sri Swarna Hospital",
"Swarup Eye Hospital and Laser Center",
"Vaatsalya Hospital",
"Vijaya Eye Hospital",
"Dinesh Medical Centre",
"Nikhil Nursing Home",
"Sree Tati Reddy Ramalinga Reddy Nursing Home",
"Sri Thati Reddy Ramalinga Reddy Nursing Home",
"Venkata Sai Baradwaja Hospital",
"7 Star Superspeciality Hospital",
"Apollo Samudra Hospitals",
"Bharani Hospital",
"Care Emergency Hospital",
"Christian Cancer Center",
"D V Raju Eye Hospital",
"Haritha Hospitals",
"Kakinada Nursing Home",
"Life Line Emergency Hospital",
"Raghava 24 Hrs Emergency Hospital",
"Rajeswari Medicals",
"Ramya Hospitals",
"Sai Sudha Hospital",
"Sapthagiri Hospitals",
"Shravani Ent Hospital",
"Siddhartha Hospital",
"Sree Bala Nursing Home Sree Bala Ent Care Centre",
"Sri Gowthami Nursing Home",
"Sri Lalitha Hospitals Institute Of Lap Surgery And Training",
"Sri Srinivasa Orthopaedic Centre and Nursing Home",
"Srihitha Children Hospital",
"Vijaya Lakshmi Nursing Home",
"Vijaya Nursing Home",
"Vishwanadha Eye and Maternity Hospital",
"Bhanu Nursing Home and Eye Hospital",
"Lifeline Emergency and Neuro Centre",
"Mother and Child Hospital",
"Nayana Eye Care",
"Ramalingeswara Nursing Home",
"Safe Emergency Hospital",
"Saipriya Maternity Hospital",
"Srujana Multi Speciality Hospital",
"Kasturi Nursing Home",
"Poly Clinic and Hospital",
"Ravichandra Hospital",
"Sanjivi Orthopaedic Hospital",
"Sri Sai Raghavendra Super Specialities Hospital",
"Sri Venkata Chalapathi Nursing Home",
"Sri Venkateswara Medicare and Research Centre",
"Sri Venugopal Hospital",
"Sudha Urology And Andrology Hospital",
"Surya Global Hospitals",
"Vasan Eye Care Hospital",
"Sarvottam Healthcare Private Limited",
"Srikiran Institute Of Ophthalmology",
"Surya Global Multispeciality and Cancer Reesearch Center",
"Sushrutha Hospital",
"Trust Hospital(A Unit Of Sarvottam Health Care)",
"Sri Srinivasa Nursing Home",
"Abhay Nursing Home",
"Aravindam Ortho and Physio Centre",
"Aruna Hospital and Poly Clinic",
"Bhaskara Raju Children Hospital",
"Life Emergency Hospital Private Limited",
"S A I Orthopaedics Trauma and General Hospital",
"Siddhartha Orthopedic Hospital and Poly Clinic",
"Sri Satya Nursing Home",
"Sri Srinivasa Hospitals",
"Sri Venkateswara Hospitals",
"Abhaya Emergency Centre",
"Adarsh Hospital",
"Alert Emergency Hospital",
"Ammanna Memorial Murtys Neuro Super Speciality Ho",
"Apex Hospital - Rajamundry",
"Aruna Hospital and Polyclinic",
"Bharadwaja Heart and Maternity Centre",
"Bhavani Nursing Home",
"Bollineni Heart Centre Pvt Ltd",
"Buddudu Orthopeadic Hospital",
"Chakradhar Hospitals",
"Coastal Cardiac And Maternity Centre",
"Geetha Mullapudi Sperspeciality Dental Hospital",
"Gowthami Nursing Home",
"Harsha Hospitals",
"Kamalakar Hospital",
"Krishna Nursing Home",
"Madhavi Nursing Home",
"Neela Jear Hospital",
"Nest Hospital",
"Netra Eye Care",
"Paramahansa Yogananda Netralaya",
"Pragati Super Speciality Hospital",
"Prasanthi Nursing Home",
"Raja Neuro And Multi Speciality Hospital Pvt Ltd",
"Rajahmundry Orthopedic Hospital",
"Ratna Orthopaedic Center",
"Sanjana Orthopaedic Hospital",
"Soujanya Hospital",
"Sreya Medical Speciality Centre",
"Sri Aditya Hospital",
"Sri Mani Orthopaedic Hospital",
"Sri Ramadas Hospitals",
"Sri Suguna Children,S Hospital",
"Supraja Hospitals",
"Surya Hospital",
"Swetha Hospitals - Rajahmundry",
"V.B. Chest Institute",
"Vasan Eye Care Hospital",
"Vijaya Hospital",
"Akira Eye Hospital",
"Dr A V R Ananda Rao Memorial Eye Clinic",
"Dr Chainulus Hospitaland Anusha Critical Carecenter",
"Gangina Hospitals",
"Kranti Nursing Home",
"Royal Hospital",
"Siddhartha Orthopaedic Hospital and Polyclinic",
"Sree Latha Hospital",
"Sri Ram Nursing Home",
"Sri Srinivasa Orthopaedic Hospital",
"Chaitanya Nursing Home",
"Goutami Eye Institute",
"Life Spring Hospital",
"Sai Hospitals",
"Sai Orthopaedics Trauma and General Hospital",
"Swatantra Hospitals",
"Saiteja Hospital",
"Adarsh Multi Speciality Hospital and Neuro Center",
"Sruthi Hospitals",
"Adarsha Hospital",
"Care Hospital",
"Konaseema Institute Of Medical Sciences",
"Konaseema Institute Of Medical Sciences",
"Konaseva Institute Of Medical Science",
"Rohine Mother and Child Care Hospital",
"Sai Leela Orthopaedic Hospital",
"Sri Konaseema Specialities Hospital",
"Sri Venkateswara Nursing Home",
"V.N.Nursing Home",
"Janatha Hospital",
"Sree Sravana Nursing Home",
"Sri Venkateswara Nursing Home",
"Vijaya Nursing Home",
"Sri Maha Laxmi Nursing Home",
"Vijaya Laxmi Nursing Home",
"Ravi Nursing Home",
"Sri Sai Bhramarambika Nursing Home",
"Sri Sankar Nursing Home",
"Susrutha Surgical and Maternity Hospital",
"Vrd Care Hospital",
"Adarsh Nursing Home",
"Kamala Nursing Home",
"Sri Venkateshwara Nursign Home",
"Bhimeshwara Hospital",
"Sri Madhavananda Speciality Hospital",
"G. S. L. General Hospital and Medical College",
"Kondreddy Nursing Home",
"Santhi Childrens Hospital",
"Sri Bikkina Nursing Home",
"Srinivasa Nursing Home",
"Subbarayudu Memorial Nursing Home",
"Narayana Reddy Eye Hospital",
"Dr.K.V.R.Hospital",
"Doctors Plaza",
"Pandu Ranga Praja Vidyasala",
"Sri Mallikarjuna Nursing Home",
"Suresh Hospital",
"Lakshmi Balaji Nursing Home",
"Sambasiva Hospital",
"Rao's Nursing Home",
"Sree Sreenivasa Hospital",
"Chopde's Nursing Home",
"Sri Varalakshmi Hospital",
"Adarsha Hospitals",
"Ahalya Nursing Home",
"Amar Orthopedics Hospital",
"Amaravathi Institute Of Medical Sciences Pvt Ltd",
"Amma Childrens Hospital",
"Aruna Hospital",
"Aswini Hospitals",
"B M R Hospitals",
"Bayya Ent Hospital And Research Centre",
"C V R Hospital",
"Chalsani Hospital",
"Coastal Care Hospital",
"Dhulipalla Hospital Pvt Ltd",
"Dr.Rangarao Nursing Home (P) Ltd",
"Guntur City Hospital-Guntur",
"Harinath Childrens Super Speciality Hospital",
"Janardani Hospital",
"Karumuri Super Speciality Hospital Pvt Ltd",
"Krishna Childrens Hospital",
"Lakshmi Meenakshi Eye and Maternity Care",
"Lalitha Super Specialty Hospital",
"Life Hospital",
"Mahathi Nursing Home",
"Maruthi E.N.T. Hospital",
"Mediline Hospital",
"Mother Theresa Multispeciality Hospital",
"Nandanaa's Multi Care Hospital",
"Padmas Hospital",
"Padmavathi Super Speciality Hospital",
"Peoples Trauma And Emergency Hospital",
"Pragathi Hospitals",
"Prof. D. Ramakotaiah Childerns Hospital",
"Purnasai Hospital",
"R K Eye Center",
"R R Speciality Hospital",
"Raghavendra Hospitals",
"Rajyalakshmi Nursing Home",
"S.G.O. Clinic",
"Sai Bhaskar Trauma and Emergency",
"Sai Chandan Eye Hospital",
"Sai Priya Hospital",
"Sai Sri Nursing Home",
"Sailaja Multispeciality Hospitals Maternity, Infertility and Trauma Care Centre",
"Sathvika Hospital",
"Shri Ramchandra Kidney Centre",
"Singh Hospital",
"Sravani Hospital",
"Sri Krishna Institute Of Medical Sciences",
"Sri Ramachandra Children and Dental Hospital",
"Sri Ramakrishna Nursing Home",
"Sri Renuka Netrayam",
"Sri Satya Sai Hospital",
"Sri Vijayasai Hospital",
"Srinivasa Nursing Hom",
"Sudarsana Eye Hospital",
"Sujatha Laparoscopy and Infertility Centre",
"Tulasi Multi Speciality Hospital",
"Vasan Eye Care Hospital",
"Veena Hospital",
"Venkata Ramana Eye Hospital",
"Venkateswara Mother and Child Hospital",
"Vijaya Orthopaedic and Trauma and Super Speciality Hospital",
"Yashaswi Hospital",
"Yerra`S Super Speciality Hospital Pvt Ltd",
"Ala Hospital",
"Aruna Multi Speciality Hospitals",
"Bmr Hospitals",
"Childrens Hospital",
"Gopala Krishna Nursing Home",
"Hi Tech Trauma And Critical Care Hospital Ltd",
"M N Hospital",
"Prasanthi Multi Speciality Hospital - Guntur",
"Pratyusha Childrens Hospital",
"Sri Bhavani Nursing Home-Guntur",
"Sri Sai Hospitals",
"Sri Sathya Sai Institute Of Orl",
"Teja Maternity Hospital And Poly Clinic",
"Sri Lakshmi Venkateswara Nursing Home",
"Raja Children's Hospital",
"St Joseph's General Hospital",
"Hyma Hospital",
"Raghuram Children Hospital",
"Sri Sruthi Hospital",
"Lakshmi Nursing Home",
"Sanjivi Orthopaedic and Physiotherapy Centre",
"Sree Geetha Eye Hospital",
"Vijaya Eye Hospital",
"Yashaswi Hospital",
"Katuri Medical College And Hospital",
"Preethi Nursing Home",
"Rachana Eye Hospital",
"Srinivasa Children Hospital",
"Adilakshmi Nursing Home",
"Datta Prasad Orthopaedic Nursing Home",
"Dr Sajja Chandramouli Hospital",
"Krishna Nursing Home",
"Nightingale Hospital",
"Ravi Cardiac and Diabetic Care Center",
"Srinivasa Nursing Home",
"Vijaya Sarada Nursing Home",
"Alapati Nursing Home",
"Amma Hospital",
"Amrutha Nursing Home",
"Devi Nursing Home",
"Dr Chadalavada Krishnaiah Multi Speciality Hospital",
"Ganga Kumari Memorial Children Nursing Home",
"Gayatri Hospital",
"Health Hospitals",
"J V M Hosppital",
"J.K Hospital",
"Kommineni Nursing Home",
"Kotnis Peoples Nursing Home",
"Sai Madhavi Nursinghome",
"Smt D Indira Memorial Meternity Nursing Home",
"Sri Srinivasa Nursing Home",
"Srijani Eye Hospital",
"Vadlamudi Hospital",
"Kims Hospital",
"Sri Teja Hospital",
"K J Memorial Hospital",
"Sri V R M Nursing Home",
"Surm Nursing Home",
"Vyshnave Nursing Home - Repalle",
"Visweswara and Gopal Krishna Nursing Home",
"Sri Ramachandra Nursing Home",
"E.S.R. Hospital",
"Sri Evuru Subbarao Memorial Nursing Home",
"Kanumuri Nursing Home",
"Krishna Nursing Home",
"Meghna Hospital",
"Nsr Memorial Children Hospital",
"Quality Hospital",
"Sanjana Speciality Hospital",
"Sree Radha Krishna Nursing Home",
"Sri Lakshmi Nursing Home",
"Sri Radha Krishna Nursing Home",
"Vamsee Specialities Hospital",
"Abhaya Multispecialty Hospitals",
"Balaji Cancer Care Centre",
"Dr Anji Reddy Multispeciality Hospitals Pvt Ltd",
"Hi Tech Trauma and Critical Care Hospital",
"Srikanth Nursing Home",
"Ramakrishna Hospital - Macherla",
"Saumya Hospital",
"Nri General Hospital",
"P.G.S.Nursing Home",
"Sree Venkateshwara Nursing Home",
"Sree Venkateswara Nursing Home",
"Amrutha Hospital",
"Bayya Ent Hospital and Research Center",
"Bommidala Cancer Institute",
"Sankara Eye Hospital",
"Trust Hospital",
"Amulya Nursing Home",
"Anantha Nursing Home",
"Asvini Nethralayam.",
"Bala Tripura Nursing Home",
"Bharathi Children Hospital",
"Mahatma Gandhi Super Speciality Hospitals",
"Mar Hospitals",
"Mother Theresa Multispeciality Hospital",
"Prasanthi Nursing Home",
"Pujita Hospitals",
"Sai Nethralayam",
"Sai Ramya Nursing Home",
"Siva Nursing Home",
"Sri Lakshmi Janaki Nursing Home",
"Sri Sai Krupa Netralayam",
"Susmitha Ortho Trauma Hospital",
"Teja Nursing Home",
"Veeraiah Chowdary Orthopaedic and Trauma Care Hosp",
"Venkateshwara Mother And Child Hospital",
"Vijaya Nursing Home",
"Visweswara and Gopalakrishna Nursing Home",
"Sowjanya Nursing Home",
"Janaki Nursing Home",
"Manju Nursing Home",
"Pragathi Nursing Home - Chilakaluripet",
"Prasad Nursing Home -Chilakaluripet",
"Ramakrishna Memorial Nursing Home",
"Sri Ratna Laxmi Nursing Home",
"G Show Reddy Memorial Nursing Home",
"Sajana Nursing Home",
"Sri Sanjivi Hospital",
"L V Prasad Eye Institute",
"Apollo Hospitals",
"Mediciti Hospital",
"KIMS Hospital, Secunderabad",
"Kamineni Hospital",
"Yashoda Hospital",
"Fernandez Hospital",
"Global Hospital",
"Asian Institute of Gastroenterology",
"Udai Clinic Orthopedic Centre",
"Homeocare International",
"Narayana Hrudayalaya Malla Reddy Hospital",
"Nizams Institute of Medical Sciences (NIMS)",
"Sathya Kidney Centre and Super Speciality Hospital",
"Sunshine Hospital",
"Basavatarakam Indo American Cancer Institute And Research Centre",
"Citizens Hospital",
"Om Sai Hospitals",
"Care Hospital, Nampally",
"Medwin Hospital",
"Universal Superspeciality Dental Hospital, Kondapur",
"Sunshine Heart Institute",
"CGHS Dispensary No.I, Charmina",
"CGHS Dispensary No.II, Humayunagar",
"CGHS Dispensary No.III,\nSecunderabad",
"CGHS Dispensary No.IV,\nBegumpet",
"CGHS Dispensary No.V,\nHumayatnagar",
"CGHS Dispensary No.VI,\nKachiguda",
"CGHS Dispensary No.VII,\nMalakpet",
"CGHS Dispensary No.VII,\nKanchanbagh",
"CGHS Dispensary No.IX,\nAlwal, Secunderabad",
"CGHS Dispensary No.X,\nAmeerpet",
"CGHS Dispensary No.XI,\nKakatiyanagar",
"CGHS Dispensary No.XII,\nDilsuknagar",
"CGHS Dispensary No.XII,\nTamaka",
"PC-I, KS Bhawan",
"PC-II, AGS Office Bldg.",
"PC Hyderabad",
"Rainbow Hospital for Women and Children, Banjara Hills",
"Rainbow Hospital for Women and Children, Secunderabad",
"Rainbow Childrens Hospital",
"Yashoda Super Speciality Hospital",
"Yashoda Super Speciality Hospital",
"Omega Hospital",
"Prime Hospital, Ameerpet",
"Prime Hospital, Kukatpally",
"Usha Mullapudi Cardiac Centre",
"Lotus Children's Hospital, Lakdikapul",
"Lotus Children's Hospital, Kukatpally",
"Omni Hospital",
"Udai Omni Hospital",
"Omni Hospital",
"Continental Hospital Limited",
"Aditya Hospital, ABIDS",
"Aditya Hospital, Uppal",
"Sai Vani Super Specialty Hospital",
"Asian Institute of Nephrology and Urology",
"Sai Sanjeevini Hospital",
"Olive Hospital",
"Ankura Hospital for Children and Women, Kukatpally",
"Ankura Hospital for Children and Women, Secunderabad",
"Ankura Children's Hospital, A.S.Rao Nagar",
"Ankura Hospital, Boduppal",
"Anupama Hospital",
"Apollo DRDO Hospital",
"Apollo Hospital",
"Apollo Hospital",
"Apollo Emergency Centre",
"Apoorva Hospital",
"Asha Hospital",
"Global Hospital, L.B.Nagar",
"Basavatarakam Indo American Cancer Hospital and Research Institute",
"Bristlecone Hospital",
"Candy Children's Hospital",
"Care Hospital",
"Guru Nanak Care Hospital",
"Challa Eye Care Centre",
"Challa Hospital",
"Clear Vision Eye Hospital",
"Disha Children's Hospital",
"Dr.Agarwal's Eye Hospital",
"Dr.Agarwal's Eye Hospital",
"Dr.Agarwal's Eye Hospital",
"Dr.Agarwal's Eye Hospital",
"Dr.Akbar Eye Hospital",
"Dr.Ramayya's Urology Nephrology Institute and Hospital Private Limited",
"Dr.Rao's ENT Super Speciality Hospital",
"Dr.Shantabai Nursing Home",
"Drishti Eye Centre",
"Eesha Multispeciality Hospital",
"Global Eye Hospital",
"Goodwill Kidney and Surgical Centre",
"Harsha Hospital",
"Himagiri Hospital",
"Hope Children's Hospital",
"Hyderabad Eye Centre",
"Hyderabad Nursing Home",
"Icon Hospital",
"J.J.Hospital",
"Janapareddy Hospital",
"Kadimi Nursing Home",
"Kamineni Hospital",
"Kamineni Fertility Centre",
"Konark Hospital",
"Lions Sadhuram Eye Hospital",
"Live Life Hospital",
"Majestic Hospital",
"Maxivision Eye Hospital",
"Matrix Hospital",
"Medwin Hospital",
"Motherhood Hospital",
"Motherhood Hospital",
"Mythri Multi Speciality Hospital",
"Malla Reddy Narayana Multispeciality Hospital",
"Neelima",
"Neelima",
"Neelima",
"NEO BBC Childrens Hospital",
"NeoRetina",
"Nova ENT",
"Pace Hospital",
"Pragna Hospital",
"Pranam Hospital",
"Prasad Hospital",
"Sridevi Nursing Home",
"Preeti Urology and Kidney Hospital",
"Raghava Multi Speciality Hospital",
"Ram Hospital",
"Remedy Hosptials",
"Sagar Lal Memorial Hospital and Matadin Goel Research Center",
"Sankhya Hospital",
"Sowmya Children's Hospital",
"Sree Netralaya Eye Hospital and Laser Centre",
"Sree Srinivasa ENT Care and Research Institute",
"Orange Hospital",
"Sri Holistic Hospital",
"Sri Srinivasa Hospital",
"Supraja Hospital",
"Suraksha Childrens Hospital",
"Surakshaka Multi Speciality Hospital",
"Swarup Eye Centre, Punjagutta",
"Swarup Eye Centre, Chapel Road",
"The Deccan Hospital",
"Udbhava Children's Hospital",
"Vcare Hospital",
"Vasan Healthcare Private Limited, Ameerpet",
"Vasan Healthcare Private Limited, Begumpet",
"Vasan Healthcare Private Limited, A.S.Rao Nagar",
"Vasan Healthcare Private Limited, Dilsukh Nagar",
"Vasan Healthcare Private Limited, Chandanagar",
"Vasan Healthcare Private Limited, Himayath Nagar",
"Vasan Healthcare Private Limited, Jubilee Hills",
"Vasan Healthcare Private Limited, Mehidipatnam",
"Vasan Healthcare Private Limited, Santosh Nagar",
"Vasan Healthcare Private Limited, Secunderabad",
"Vasan Healthcare Private Limited, Kukatpally",
"Vijay Marie Hospital",
"Vijaya Health Care",
"Xenia Multi Speciality Hospital",
"Gandhi Medical College and Hospital",
"Amma Hospital",
"Anurag Hospital For Children",
"Aval Hospital For Women and Children's Hospital",
"Chandamama Hospital",
"Deepak Nursing Home",
"K.B.Hospital",
"L V Prasad Eye Institute",
"Mamata Childrens Hospital",
"Peoples Clinic",
"Prabha Nursing Home",
"Pragya Eye Hospital , Phaco Surgical Centre",
"Rajeshwari Ghospital",
"Sankar Eye Hospital",
"Sri Arvind Hospital",
"Sridevi Eye Hospital",
"Suresh Ortho Hospital",
"V.G.R. Diabetes Specialities Hospital",
"Vijetha Health Care and Research Center P) Ltd",
"Yalamanchi Hospitals and Research Centres Pvt Ltd",
"Andhra Hospitals",
"Anu Hospitals",
"Anurag Institute Of Medical Sciences",
"Arun Kidney Centre",
"Aswinee Nursing Home",
"Bhargav Nursing Home and Eye Hospital.",
"Chaitra Hospitals Surgical And Maternity",
"Charitha Sri Hospitals Ltd",
"City Cancer Centre",
"Giffard Memorial Hospital",
"Giridhar Ent Hospital",
"Harini Gastro and Liver Centre",
"Hasini Hospitals",
"Help Hospital Pvt Limited",
"Ishwarya Maternity Hospital",
"Kamala Orthopeadic Nursing Home",
"Klmm Hospital Pvt Ltd",
"Krishna Gastro and Liver Center-Safe Hospitals",
"Latha Superspecialities",
"Life Line Trimurthy Hospital",
"M V S Accident And Trauma Centre",
"M/S Azam Hospital",
"Meenakshi Eye Hospital",
"Metro Superspeciality Hospitals",
"Modern Retina Centre",
"Mother and Child Hospital and Family Hospital",
"Myneni Hospital For Orthopaedic and Accident Care",
"Padmaja Clinic Womens And Multispeciality Hospital",
"Peoples Poly Clinic - Vijayawada",
"Praja Vydyasala",
"Prasanthi Hospital",
"Prasanti Nursing Home",
"Praveen Cardiac Center",
"Preethi Childrens Hospital",
"Purna Heart Institute",
"R V R Hospitals",
"Raavella Eye Hospital",
"Rajeswari Hospital",
"S.K. Super Speciality Laser Eye Hospital",
"Safe Hospital",
"Sai Krishna Hospital",
"Sai Ram Maternity Hospital",
"Sai Swetha Mother And Child Hospital",
"Sandhya Hi-Tech Vision Care Center",
"Sankara Eye Hospital",
"Sathish Urology and Andrology Center",
"Sekhar Ortho Center",
"Shri Shiridi Sai Speech and Hearing Institute",
"Sindhura Hospital",
"Singari Ent Hospital And Research Centre",
"Sree Neelima Nursing Home",
"Sree Sarada Nursing Home",
"Sreya Nursing Home",
"Sri Sai Hospital",
"Sri Srinivasachildrens Hospital",
"Sri Venkata Sai Urology and Maternity Center",
"Sri Venkatasai Urology and Maternity Centre",
"Sridevi Eye Hospital",
"Srivenkasai Urology and Maternity Center",
"St. Ann Hospital",
"Sumanth Nursing Home",
"Suraksha Hospital",
"Suraksha Neuro Center",
"Udaya Eye Hospital",
"Vasan Eye Care Hospital",
"Vignesh Hospitals",
"Vijay Orthopaedic And Accident Care",
"Vijaya Super Speciality Hospital",
"Vijayachandra Nursing Home",
"Vijayawada Ent Hospital",
"Vijayawada Institute Of Neuro Sciences (Vins)",
"Vijaywada Nursing Home and Polyclinic (P) Ltd",
"Vinayasree Nursing Home",
"Meher Hospitals",
"Noori Mother and Child Hospital",
"Prasanthi Hospitals",
"Rainbow Children's Hospital",
"Currie City Cancer Center",
"Health Care Global Curie City Cancer Centre - Vijayawada",
"Thammineni Hospital and Diagnostic Centre",
"Dr B Venkataratnam",
"Heart Care Centre",
"Nagarjuna Hospital Ltd",
"Nandini Hosipital",
"Pinnamaneni Polyclinic",
"Ramana Gastrolaparoscopy and Multi Speciality Hospital",
"Rich Hospital",
"Time Hospitals Pvt Ltd",
"Aayush Nri Lepl Health Care Pvt Ltd",
"City Cardiac Research Center Ltd",
"Dr. Ramesh Cardiac and Multi Speciality Hospital Limited",
"Lakshmi Eye Maternity and Laproscopy Hospital",
"Sentini Hospitals Pvt Ltd",
"Surapaneni Eye Hospital",
"Vennela Mother and Child Hospital",
"Ashraf Maternity and Ent Hospital",
"Care Hospital - Vijayawada",
"Chaitanya Eye Hospital",
"Chinnari Hospital",
"Citi Orthopedic Centre",
"Emergency Vijaya Hospitals",
"Krishna Institute Of Medical Sciences Limited",
"Lakshmi Nurisng Home, Vijayawada",
"Maxivision Laser Center Pvt Ltd-Vij",
"Nagarjuna Hospital",
"Padmavathi Hospital Mother and Child Care Cntre",
"Positive Pulse Hospitals",
"Prashant Hospital - Vijayawada",
"Raja Nursing Home",
"Rameeza Orthopaedic Centre",
"Royal Hospitals",
"Santhi Nursing Home",
"Sowmya Hospital",
"Sree Jayalakshmi Nursing Home",
"Sree Venkateswara Nursing Home",
"Sriram Hospitals",
"Svr Neuro Hospital",
"The Orthopaedic Nursing Home",
"The Pujitha Hospital",
"Trust Hospital",
"Usha Cardiac Centre Ltd",
"V.R.L.S. Memorial Neuro Hospital",
"Vasavya Nursing Home",
"Vijaya Durga Nursing Home",
"Life Spring Hospitals",
"Lata Hospital",
"Yakkala Jyothi Hospital",
"Chikitsa General Hospital",
"St Anns Health Center",
"Aswani Nursing Home",
"Balaji Nursing Home",
"Brundavan Nursing Home",
"Lakshmi Womens Hospital",
"Rajeevi Nursing Home",
"Shree Rajeevi Nursing Home",
"Shri Madhu Hospitals",
"Sri Balaji Nursing Home",
"Sri Madhu Hospital",
"Sri Venkateswara Nursing Home",
"Srinivasa Nursing Home",
"Vani Hospitals",
"Varadarajula Memorial Eye Hospital",
"Venkatrama Nursing Home",
"Viswa Chakra Orthopaedic Hospital",
"Life Spring Hospital",
"Rama Nursing Home",
"Padmavathi Hospital",
"Boppana Superspeciality Hospital",
"Bhargavi Nursing Home",
"Rotary Eye Hospital",
"Samat Nursing Home",
"Usha Nursing Home",
"Punnaiah Memorial Mother and Child Hospital",
"Sri Rama Hospital - Jaggayyapet",
"Sri Swathi Maternity and Surgical Nursing Home",
"Srujana Nursing Home",
"Kranthi Hospital",
"Sailaja Nursing Home",
"Praja Hospital",
"Dr Mohanarao Memorial Super Speciality Hospital",
"Matha Nursing Home",
"Dr. Pinnamaneni Siddhartha Institute Of Medical Sciences Hospital / Dr. Psims Hospital",
"Anuradha Ent Hospital",
"Padmavathi Hospitals",
"Sacred Heart Hospital",
"Shreerama Nursing Home",
"Sri Rama Nursing Home",
"Sri Sai Rathna Eye Hospital",
"Sri Venkateswara Nursing Home",
"Uma Childrens Hospital",
"Kamineni Hospital",
"Lakshmi Nursing Home",
"C N Hospitals",
"Dr.Bethune Nursing Home",
"K M Hospital",
"M.H Hospital",
"Murthy Ortho Hospital",
"New Balaji Super Speciality Hospital",
"Sri Raja Raghavendra Nursing Home",
"Sri Vamsi Krishna Hospital",
"St. Theresa Hospital",
"Vijaya Super Speciality Hospital",
"Adithya Test Tube Baby Centre",
"Amma Hospital",
"Apple Orthopaedic Hospital",
"Gowri Gopal Hospital Pvt Ltd",
"Kurnool Heart and Brain Centre",
"Modern Eye Hospital and Research Centre",
"R V Hospital",
"Sree Aswini Hospital",
"Sri Vijaya Durga Cardiac Centre",
"Surya Hospital",
"Suseela Netralaya and Maternity Hospital",
"Vijaya Hospital",
"Viswa Bharathi Super Speciality Hospital",
"Aayushman The Family Hospital",
"New Noble Super Speciality Hospital",
"Padma Chandra Super Speciality Hospital",
"Balaji Hospital-Kurnool",
"Bangalore Super-Speciality Hospital",
"Deepak Tej Hospital",
"Gvr Hospitals",
"Karthik Hospital",
"R R Hospitals",
"Rainbow Institute Of Child Health and Maternity Hosp",
"Saraswathi Nursing Home",
"Siri Noble Hospital",
"Sri New Balaji Super Speciality Hospital",
"Sri Venkateswara Super Speciality Hospital",
"Tcr Multispeciality Hospital",
"Desai Nursing Home",
"Krishna Hospital",
"Vijayalakshmi Nursing Home",
"Aditya Nursing Home",
"Anasuya Child Hospital",
"Saranya Nursing Home",
"Vishwa Bharati Cancer Hospital",
"Gelvi Nursing Home",
"Gupta Hospital, Nandyal",
"Kvr Hospital",
"Madhumani Nursing Home",
"Murali Hospital",
"Narmada Nursing Home",
"Nayana Eye Care and Research",
"Neravati Hospital",
"R R Hospital",
"S.V.D. Nursing Home",
"Saivani Hospital",
"Sanjeevini Nrsing Home",
"Shantharam General Hospital",
"Sree Durga Nursing Home",
"Sri Balaji Nursing Home",
"Sri Venkata Devanath Nursing Home(S.V.D.)",
"Swami Super Speciality Netralayam And Skin Care Centre",
"Amma Hospital",
"Anasuya Institute Medical Sciences",
"Aravind Kidney Centre",
"Aravind Nethralaya Meenakshi Diabetes and Endocrinology Centre",
"Bhaskar Reddy Hospital",
"Deepthi Nurisng Home",
"Dr Andals Lakshmi Fertility Research and Laparoscopic Surgical Centre",
"Dr P Madhusudhana Sastry Hospital",
"Dr.P.V.Ramchandra Reddys Peoples Polyclinic",
"Guram Chilren Hospital",
"Lakshmi Fertility Research and Laparoscopic Surgical Center",
"Lalitha Eye Hospital",
"Lalitha Hebbar Nursing Home",
"Latha Matrnity and Children Hospital",
"Life Spring Hospital",
"Madurai Netralaya",
"Modern Eye Hospital And Research Centre",
"SPSR Nellore Hospital and Research Center",
"Nizams Little Star Children Hospital",
"R K Eye Care Center",
"R.S.R.Hospital",
"Ramakrishna Diabetes Research Center",
"Rich Hospitals",
"S S Hospital",
"Sailaja Nursing Home - SPSR Nellore",
"Sireeha Netralaya",
"Sri Durga Hospital and Brain Center",
"Sri Ramachandra Nursing Home",
"Sri Ratnam Hospital",
"Sri Sai Patham Hospitals",
"Susrutha Uro Renal Hospital",
"Thanuja Maternity Hospital",
"Vasan Eye Care Hospital",
"Venkataramana Hospital",
"Viajya Hospital (A Unit Of Vijaya Krishna Hospitals Pvt Ltd)",
"Vijaya Hospital",
"Narayana General Hospital And Super Speciality Hospital",
"Ahalya Devi Nursing Home - SPSR Nellore",
"Bolleneni Super Speciality Hospital",
"Kavitha Nursing Home",
"Vaishnavi Clinic",
"C.R. Reddy Hospital",
"Jayabharat Hospital",
"Mydhili Hospital",
"Shar Hospital",
"Seshama Naidu Hospital",
"Sri Sadana Nursing Home",
"Srinivasa Nursing Home",
"Vamsi Nursing Home",
"Aravind Eye and Diabetes Clinic",
"Kandukuri Hospital",
"Life Care Hospital",
"Ravi Nursing Home",
"Sri Padmavathi Nursing Home",
"Usha Nursing Home",
"K.M. Hospital",
"Vijaya Hospital",
"Dr Bsr Hospital",
"Amma Eye Hospital Ongole",
"Aravind Eye Hospital",
"G S R Hospital",
"K V Nursing Home",
"Kommalapati Veeraiah Nursing Home",
"Mps Memorial Hospital",
"Nalluri Nursing Home",
"Padmavathi Nursing Home",
"Prasad Vydyasala",
"Rambabu Hospital",
"Ravi Mother and Child Hospital",
"Samata Hospital Orthopaedic and Maternity Hospiital",
"Sanghamitra Hospital Pvt Ltd",
"Sundara Raja Nursing Home",
"Vaatsalya Hospital ( Ongole)",
"Vijaya Hospital",
"Yamini Eye Care - Prakasam",
"Ajmal Nursing Home",
"Amrutha Heart Hospital",
"Aneesh Kidney Centre",
"Bharathi Nursing Home",
"Chandamama Children Hospital",
"Devi Hospital",
"Durga Nursing Home- Anjaiah Road",
"Manasa Mother and Child Hospital",
"Modern Eye Hospital and Research Centre",
"Pranathi Neuro Speciality Hospital",
"Sai Nursing Home",
"Sevita Nursing Home",
"Sri Lakshmi Nursing Home",
"Srinivasa Hospital",
"St Xaviers Hospital",
"Venkata Ramana Nursing Home",
"Vijaya Hospital",
"Doctor Sivarami Reddy Hospital",
"Pragathi Nursing Home",
"Dr Kotareddy Hospitals",
"Harini Peoples Clinic",
"Muppa Rosaiah Hospital",
"Baer Hospital",
"Hyma Hospital",
"Prema Hospital",
"Rajyalakshmi Hospital",
"Ravi Nursing Home",
"Sankar Nursing Home",
"Solomon Nursing Home [Chirala]",
"Sree Naga Sayan Nursing Home",
"Sree Sai Childrens Hospital",
"Sri Saraswathi Nursing Home",
"G.K.M. Nursing Home",
"Vijaya Nursing Home",
"G.V.K. Nursing Home",
"Jhansi Nursing Home",
"Sreenivasa Multi Speciality Hospital",
"Peoples Nursing Home",
"Sri Lakshmi Mallikarjuna Gastro and Laproscopy Centre",
"Bandaru Rangayya Yadav Memorial Trust Association",
"Adithya Hospitals",
"Amma Hospital",
"Amrutha Hospital",
"Arunodaya Hospital",
"Deepa Nursing Home",
"Gmr Varalaxmi Care Hospital",
"K C Eye Hospital",
"Kims Sai Seshadri Hospital",
"Krishna Nursing Home",
"Mgm Hospital",
"Mithra Maternity Nursing Home and Infertility Centre",
"Pavani Nursing Home",
"Sanjeevini Hospital",
"Santhi Nursing Home",
"Sarojini Devi Hospital",
"Sindhura Hospitals",
"Sri Surya Hospital",
"Vijaya Harsha Mother And Child Hospital",
"Vijaya Surgical Speciality Hospital",
"Sri Sai Satyanarayana Nursing Home",
"Sri Srinivasa Nursing Home",
"Sri Sathya Sai Medical Center",
"Aparna Dantham Nursing Home",
"Sitarama Nursing Home",
"Sri Rajeshwari Nursing Home",
"Annapoorna Hospital",
"Arogyavaram Eye Hospital and Contact Lens Clinic",
"Kanaka Durga Nurisng Home",
"Mahalaxmi Nursing Home",
"Revatirupathi Hospital",
"Srinivas Nursing Home",
"Susrutha Nursing Home",
"Shanti Nursing Home",
"Bharat Speciality Hospital",
"Vaatsalya Hospital",
"Sri Srinivasa Nursing Home",
"Canossa Hospital",
"Sraddha Hospital",
"T.Narayana Rao",
"Visakhapatnam Steel General Hospital",
"A N Beach Hospital",
"Aarif Nursing Home",
"Abc Hospital",
"Abhaya Critical Care",
"Adarsha Orthopaedic Center",
"Apex Hospital",
"Bharathi Hospital",
"C.S.R. Hospital",
"Care Hospital - Maharanipet",
"Cdr Hospital,Vishakhapatnam",
"City Care Hospital",
"Genesis Children Hospital",
"Indus Hospitals",
"Kanakadurga Hospitals Pvt Ltd",
"King George Hospital",
"Krishna Hospital - Visakhapatnam",
"Lazarus Hospitals Ltd",
"Manipal Hospital",
"Mythri Nursing Home",
"Pallavi Hospital",
"R.K. Children's Hospital",
"Race Hospital",
"Rhea Hospital Metroxmulti Speciality Hospital)",
"Rk Children Hospital and Perinatal Centre",
"Sagara Durga Hospital",
"Samudra Hospitals",
"Saryu Multicare Hospital",
"Sevenhills Hospital Ltd.",
"Shri Krishna Child Care Centre",
"Shri Venkataramana Hospital",
"Siddharth Hospital",
"Simhadri Hospital",
"Sree Uma Hospitals P Ltd",
"Sri Sagara Durga Medicals",
"Sri Venkataramana Hospital",
"St. Joseph's Hospital",
"Vaishnavi Hospital",
"Vasan Eye Care Hospital-Visakhapatnam",
"Vijaya Medical Centre",
"Vijetha Hospital",
"Visakha Children Hospital",
"Apollo Heart Hospital",
"Free Polio Surgical and Research Foundation",
"Subham Prema Hospital",
"Visakha Ent Hospital",
"Dr Rama Rao Hospital",
"Kothagiri Surya Nursing Home",
"Sri Chakra Multi Speciality Hospitals Pvt Ltd",
"Sun Multi Speciality Hospital",
"Devi Priya Life Care Hospial",
"Sri K V Punnaiah Memorial (Hymavathi Nursing Home)",
"St.Ann's Jubilee Memorial Hospital",
"Bharath Hospital",
"Cancer Treatment and Research Center",
"Krishi Trust Hospital",
"Nikitha Hospital",
"Padmaja Hospital",
"Queens Nri Hospital / Chalasani Hospitals Private Limited",
"Raghavendra Hospital",
"Rama Hospitals",
"Suma Maternity Home",
"The Good Samaritan Homoeo Hospital",
"Vizag Orthopaedics and Special Surgery",
"Dj Clinic",
"Abhi Multi Speciality Hospital",
"Annapoorna Hospital",
"Anupama Surgical And Children Hospital",
"Apoorva Hospital",
"Care Dental Hospital",
"Good Health New Central Hospital",
"Kala Hospitals Pvt Ltd",
"Kalavathi Surgical Hospital and Laparoscopic Centre",
"Krishna Maternity And Nursing Home  Visakhapatam",
"Maxivision Laser Centre Pvt Ltd",
"Navya Hospital",
"Padmasri Hospital    Vishakhapatnam",
"Sai Spoorthy Hospital",
"Venkatarama Hospital",
"Visakha Gyn and Obs Hospital",
"Vision Care Center( Super Speciality Eye Hospital )",
"M.G.R. Hospital",
"Mahama Gandhi Cancer Hospital and Research Institut",
"Mvp Hospital",
"Sanjivi Hospital",
"Uma Polyclinc and Hospital",
"Vijaya Hospital",
"Visakha Eye Hospital",
"Waltair Multicare Hospital",
"Kamala Nursing Home",
"Care Hospitals",
"Gajuwaka Hospital P Ltd",
"Lawrance and Mayo Hospital",
"Lion Dist 324 C, Cancer Treatment and Research Center",
"Prabha Clinic and Nursing Home",
"Amrutha Nursing Home Private Limited",
"Gowtami Hospital",
"Padmaja Hospital",
"R K Hospital: Gajuwaka Hospitals (P) Ltd. - Visakhapatnam",
"S.J.Hospital",
"Sri Rama Hospital",
"Sujatha Hospital",
"Susruta Hospital",
"Satyam Intensive Care and Trauma Centre",
"Sr Hospital",
"L V Prasad Eye Institute Vishakapatnam",
"Sai Satya Hospital",
"Sankar Foundation Eye Hospital",
"Anakapalie Orthopaedic and Maternity Hospital",
"Annapoorna Babycare and General Hospital",
"Aswini Clinic, Maternity and Nursing Home",
"Ramyasai Nursing Home",
"Sb Eye and Maternity Hospital",
"Venkatarama Hospital",
"Vijaya Hospital",
"Vikram Hospital",
"Gayatri Nursing Home",
"Venkatarama Hospital",
"St.Ann's Hospital",
"Sunitha Nursing Home",
"Sri Rama Mother and Child Hospital",
"Amg Hospital",
"Sunita Nursing Home",
"Sri Lalitha Nursing Home",
"Sri Venkateshwara Hospital",
"Sri Subrahmanyam Nursing Home",
"Prasanna Surgical Nursing Home",
"Krishna Nursing Home",
"Radha Krishna Nursing Home",
"Sri Sathya Day and Night Hospital",
"Archana Bhaskar Nursing Home",
"Bharath Hospital",
"Swamy Eye Hospital",
"Venkata Rama Hospital",
"Venkateswara Nursing Home Orthopaedic Center",
"Andhra Children Hospital",
"Jyothi Nursing Home",
"Muvva Gopala Hospitals Pvt Ltd",
"Pushpagiri Eye Hospital",
"Sree Krishna Nursing Home",
"Sri Sai P.V.R. Hospitals",
"Vaatsalya Hospital",
"Vamsi Nursing Home",
"Venkata Padma Hospital",
"Vijaya Hospital",
"Vikas Hospital",
"Shalom Medical Centre",
"Sri Sai Super Speciality Hospital",
"Tirumala Nursing Home",
"Uday Nursing Home",
"O.E.U.Lions Eye Hospital",
"Maharajahs Institute Of Medical Sciences",
"Jayasree Hospital",
"Karshaka Maharshi Hospital",
"Sri Krishna Nursing Home",
"Bobbili Eye Hospital (P) Ltd",
"Sri Hanuman Children Hospital",
"Sri Ramakrishna Clinic and Nursing Home",
"Sai Ramya Nursing Home",
"Prashanti Hospitals Uro Gyneac Infertility Centre",
"Bhuvaneshwari Hospital",
"Dr M Prabhavathi",
"Kamala Hospitals",
"Lokendra Nursing Home",
"Mahalakshmi Hospitals",
"Mother Child Hospital",
"Sankara Netra Chikitsalaya",
"Sri Sai Madhavi Hospital",
"Sri Venkateswara Nursing Home",
"Swaruparani Nursing Home - Eluru",
"Vamsi High Tech Super Speciality Hospital",
"Vijaya Hospital, Eluru",
"Yasoda Hospital",
"Asram Hospital (Alluri Sita Rama Raju Academy Of Medical Sceinces)",
"Asrims Hospital",
"Kay Vee Hospital",
"Shri Krishna Mother and Child Hospital",
"Indira Devi Memorial Nursing Home",
"Mother Vannini Hospital",
"Prasad Hospitals",
"Sri Venkateswara Netralaya",
"Veenus Nursing Home",
"Ch. Varalakshmi Nursing Home",
"Sri Venkata Ramana Nursing Home",
"Krishna Hospital",
"Nallaparaju Venkata Raju Hospital",
"Neeladri Hospital",
"Pallavi Hospital",
"Sai Hospital",
"Jnananda Retina Foundation Pvt Ltd",
"Madhu Chalapathi Urological Hospital",
"Radha Krishna Netralaya",
"S.V.R. Maternity Hospital",
"Siva Srinivasa Ent Hospital",
"Sri Kanaka Durga Nursing Home",
"Sri Krishna Eye Institute",
"Sri Lakshmi Hospital",
"Subhadra Surgical and Maternity Centre",
"U.V.S.M. Eye Hospital",
"Varma Heart Care Center",
"Bhimavaram Hospitals",
"Siri Hospital",
"Apple Hospital",
"Better Vision Clinic",
"Bhagyasri Hospitals",
"Bharathi Nursing Home, Tanuku",
"Geeta Hospitals-Tanuku",
"Lakshmi Arundhati Nursing Home",
"Mullapudi Venkatarayudu Eye Centre",
"Sai Swetha Hospital",
"Sanjeevani Emergency Hospital",
"Sree Satya Hospitals",
"Sreeharsha Ent Hospital",
"Sri Balaji Hospital",
"Sri Chaitanya Orthopaedic Hospital",
"Sri Janaki Hospitals",
"Sri Ramakrishna Orthopaedic and Physiotherapy Center",
"Sri Ramana Childrens Hospital",
"Sri Sai Orthopedic And Sri Sai Inferlility Hospital - Tanuku",
"Sri Satya Sai Nursing Home and Laproscopic Surgical Center",
"Sri Surya Nursing Home",
"Sri Venkata Ramana Nursing Home",
"Srinivasa Mother and Child Care Centre",
"St. Mary Hospital",
"Sudha Hospital",
"Suraksha Health Care P Ltd",
"Vijaya Nursing Home",
"Lakshmi Hospital Eye And Maternity Hospital",
"Haritha Hospital",
"Krishna Bhavani Hospital",
"Sai Bhargavi Eye Hospital And Excimer Laser Centre Pvt Ltd",
"Sri Sai Orthopaedic and Maternity Hospital",
"Sri Surya Nursing Home",
"Suryaprakasam Nursing Home",
"Tirumala Nursing Home",
"Vamsi Superspeciality Hospital",
"Aswani Mother and Child Hospital",
"Janaki Hospital",
"Narsapur Christian Hospital",
"Sowbhagya Hospital",
"Sri Sai Paediatric and Neuro Psychiatric Hospital",
"Sri Surya Hospital",
"Katragadda Nursing Home",
"Our Lady Of Health Hospital",
"Jibilli Mother and Child Hospital",
"Nirmala Hospital",
"Siva Speciality Hospital",
"Soujanya Hospital",
"Centre For Sight",
"Centre For Sight, Rajahmundry",
"Centre For Sight, Banjara Hills",
"Centre For Sight, Basheerbagh",
"Centre For Sight, Kadapa",
"Centre For Sight, Kurnool",
"Manipal Super Specialty Hospital",
"VIMHANS Hospital",
"Assa Diagnostics and Nursing Home",
"General Hospital, Pasighat",
"Ramakrishna Mission Hospital",
"Polo Hospital Pvt Ltd",
"Tara Memorial Hospital",
"Arunachal State Hospital, Naharlagun",
"B T M Hospital",
"Boriatari Memorial Hospital",
"Tawang District Hospital",
"District Hospital",
"Fakhruddin Ali AhmedMedical Collegeand Hospital",
"Bhagawani Devi Prasuti Sadan",
"Sanjivani Hospital And Rcs Ltd",
"R N B Civil Hospital",
"Chilarai HospitalandResearch Centre",
"Indian Oil Corporation Limited Assam Oil Division Hospital Digboi Assam",
"Lower Assam Hospital And Research Centre",
"S.M. Hospital and Diagnostic Centre",
"Swagat Hospital And Research Centre",
"Silchar Medical College and Hospital (SMCH)",
"Arnav Memorial Hospital",
"Indian Red Cross Society",
"Kay Cee Clinic and Nursing Home",
"Lions Eye Hospital",
"Mawsumi Hospital and Research Center",
"R . E. Nursing Home and Diagnostic",
"Siva Sundari Narisikshasram and Ante-Natal Clinic",
"Mediland Hospital and Research Centre",
"Greenview Nursing Home",
"Life Line Hospital",
"Silchar Medical College and Hospital",
"Medinova Hospital and Research Centre",
"South City Hospital",
"Valley Hospital And Research Centre Pvt Ltd",
"Mangaldol Poly Clinic",
"Ghilamora CHC",
"Civil Hospital",
"Gauripur Hospital",
"Astha Hospital Dibrugarh",
"Dr Damani's Nursing Home",
"Drishti Netralaya",
"Jj Memorial Diagnostics And Hospitals Pvt Ltd",
"Medicare Diagnostic And Hospital",
"Srimanta Sankardeva Hospital And Research Institute",
"Urovision Diagnostics and Reaearch Center Pvt Ltd",
"Vincenza Gerosa Hospital",
"Assam Medical College Hospital Dibrugarh (Assam)",
"Aditya Diagnostics and Hospitals",
"Archana Trauma and Orthopaedics Hospital and Research Centre",
"Brahmaputra Diagnostic and Hospital Ltd",
"H.M.Poly Clinic and Diagnostics Centre",
"Marwari Arogya Bhawan Hospital",
"Sristi Hospitals And Research Centre Pvt Ltd",
"Tengakahat PHC",
"Life Care Nursing Home",
"Sasoni CHC",
"Rajgarh CHC",
"Assam Medical College and Hospital (AMCH)",
"Florence Hospital",
"Solace Hospital and Research Centre",
"Seven Sisters Medical Service Ltd - Goalpara",
"Garmur CHC",
"Binapani Nursing Home and Hospital",
"Vivekananda Kendra-Nrl Hospital",
"Naharani PHC",
"G B M Nursing Home",
"Hgm Nursing Home",
"Life Line Hospital and Research Centre",
"CGHS Dispensary No.I",
"CGHS Dispensary No.II",
"CGHS Dispensary No.III",
"Jorhat Medical College And Hospital",
"A G Nursing Home",
"J D S Civil Hospital",
"J R Hospital",
"Jorhat Nursing Home",
"Jyoti Diagnostics",
"K. G Memorial Medical Centre",
"Kamalabari Sdch",
"Malpani Nursing Home Medicure Center)",
"Pain and Fracture Clinic and Research Centre",
"Prava Eye Hospital",
"Sanjivani Hospital",
"Titabor Sd Ch",
"Institute Of Medical Science and Research Pvt Ltd",
"Gauhati Medical College and Hospital (GMCH)",
"Banajit Choudhury",
"Central Clinic and Nursing Home",
"Guwahati Netralaya Eye Hospitaland Rclkmeh",
"Sri Sankaradeva Nethralaya",
"Wintrobe Hospital",
"Barthakur Clinic Pvt Ltd",
"Aruna Memorial Hospital",
"Dispur Hospitals Pvt Ltd",
"G N R C Heart Institute",
"Gauhati Medical College Hospital",
"Guwahati Eye Hospital",
"International Hospital",
"Midland Hospital",
"Nemcare Hospital",
"Nightingale Hospital",
"Advance Neuro Science Hospital",
"Diabetic Care and Research Centre",
"Dispur Polyclinic and Nursing Home",
"Down Town Hospital Ltd.,",
"Good Health Hospital - Guwahati",
"Guwahati Neuro Research Centre Ltd",
"Sun Valley Hospital - Guwahati",
"City Heart Hospital",
"Sacred Home Hospital and Research Clinic",
"Arya Hospital (A Unit Of North Eastern Medical Research Institute Ltd)",
"Gurucharan Polyclinic Cum Nursing Home",
"Marwari Hospital and Research Centre",
"Satribari Christian Hospital",
"Goenka Nursing Home",
"Institute Of Human Reproduction",
"Kumars Nursing Home",
"Swagat Endolaproscopic Surgical Research Institute",
"Sanjevani Hospital",
"Green Land Nursing Home And Medhi Diagnostic Clinic",
"Dr Bhubaneswar Borooah Cancer Institue",
"Dr. Kalicharan Das Nursing Home and Polyclinic",
"Saraighat Hospital Pvt Ltd.",
"Dharanidhar Memorial Institute Of Medical Science And Research (Dims)",
"East End Nursing Home and Research Institute",
"Pragjyothi Eye Care And Research Centre Pvt Ltd",
"Agile Hospitals Pvt Ltd",
"Gnrc Sixmile Hospital",
"North East Cancer Hospital And Research Institute",
"Institute Of Child and Woman Health Care(A Unit Of Dr Kuntal Goswami Memorial Trust)",
"Assam Lithotripsy Centre",
"Ramcharan Foundation",
"Guwahati Medical College Hospital",
"Hayat Hospital",
"Pratiksha Hospitals",
"Hm Hospital and Research Centre Pvt.Ltd",
"Hajo Fru",
"Sualkuchi Fru",
"Dr. Dhani Ram Baruah Heart Institute and Research Ce",
"Bezara Fru",
"Boko Fru",
"Rangia Poly Clinic and Nursing Home",
"Tularam Bafna Civil Hospital",
"Catholic Health Center (Hospital) Diphu",
"Dotma CHC",
"Balajan Block PHC",
"Megacare Multispeciality Hospital Pvt Ltd",
"Bihpuria CHC",
"Dalpur CHC",
"Happy Nursing Home",
"Mid Town Hospital and Research Institute",
"Saumerpith Nursing Pvt Ltd",
"Nowboicha CHC",
"Bongalmora CHC",
"Dhakuakhona CHC",
"Haibargaon Nursing Home",
"Haji Abdul Majid Memorial Hospital and Research Centre",
"Kapili Hospital And Research Centre",
"G.D.Hospital",
"Nagaon Nursing Home and Maternity Home",
"Pkb Nursing Home Pvt Ltd",
"Pragati Nursing Home/Diacare",
"United Hospital And Research Centre",
"Choudhary Maternity Clinic",
"Dhl Health Services",
"East Point Hospital And Res Centre",
"Life Care Hospital and Research Centre",
"Pragati Hospital And Research Centre",
"Sampreeti Hospital",
"Sarma Nusring Home",
"H M Hospital and Research Center",
"Moran Medical Centre",
"Tezpur Medical College and Hospital",
"B. K Memorial Hospital - Tezpur",
"Baptist Christian Hospital",
"E M M Hospital And Research Centre",
"Gogoi Nursing Home Complex",
"Skylark Hospital and Rese",
"K P Memorial Hospital",
"Biroja Hospital",
"Borthakur Nursing Home and Research Centre",
"City Hospital And Research Centre",
"Dr Bawaris Nursing Home",
"Jeevan Jyoti Nursing Home",
"Life Line Hospital - Tinsukia",
"Pinewood Hospital",
"St Lukes Hospital",
"Tinsukia Ortrhopaedic Clinic, Hospital And Researc",
"M R Agarwal Memorial Diagnostics and Hospital",
"Cherish Hospital and Diagnostic Center",
"Margherita Community Health Centre",
"Munaf Memorial Hospital and Research Center",
"Rontix Hospital",
"Abhinav Hospital",
"Jeevan Jyoti Orthopedic Emergency And Trauma Center",
"Lovely Nursing Home",
"Mohini Devi Rungta Hospital",
"Sadar Hopital Araria",
"The Rural Institute Of Medical Aids",
"Baba Gramin Seva Sadan",
"Dr. Alakh Niranjan Memorial Hospital",
"Dr. Chaudhary Hospital and Research Institute",
"Mata Mariam Nursing Home",
"Kumar Ortho and Maternity Home",
"Shishu Kalyn Kendra",
"Arwal Surgical And Orthocare Centre",
"Khursheed Ahmad Memorial Hospital",
"Pipra Hospital Pvt.Ltd",
"Royson Meaternitey and Nursing Home",
"Aastha Nursing Home",
"Haddi and Dental Hospital",
"Health World",
"Pulse Women Hospital",
"S D Hospital",
"Samarth Eye Hospital and Laser Surgery Centre",
"Shanker Nursing Home",
"Swastik Hospital",
"Magadh Clinic",
"Dord Hospital",
"Rahat Clinic",
"Badri Ortho Clinic",
"Dr Ajay Kumar",
"Dr Sailja Jha",
"Dr Sumitra Choudhary",
"Dr. Akhilesh Kumar",
"Dr. Gayatri Choudhary",
"Dr. Hemant Kumar Das",
"Surgery Centre",
"Garib Nawaz Clinic",
"S Ansari Nursing Home",
"Baba Baidynath Eye Hospital",
"Advanced Ent and Head Neck Hospital",
"Ananya Nursing Home",
"Aradhana Clinic",
"Arora Nurnig Home",
"B. P. Rai Memorial Hospital",
"Balia Referal",
"Bhushan Maternity Clinic",
"Bone and Joint Hospital and Trauma Centre",
"Diabetes and Heart Research Centre",
"G. Lall Memorial Hospital",
"Hope Hospital",
"Jivan Suraksha",
"Jyoti Hospital",
"Mahavir Shalya Sansthan",
"Mahila Aspatal",
"Medicare and Heart Centre",
"Mira Nursing Home",
"Ortho Centre",
"Perwez Alam Poly Clinic",
"Ritul Health Care Centre",
"S.S.M.Maternity Hospital",
"Shishu Chikitsalaya",
"Shivani Health Care Centre",
"Shree Agrasen Matri Seva Sadan",
"Shreshtha Surgical and Maternity Hospital",
"Surya Clinic",
"Tara Ent Clinic",
"Uma Nursing Home",
"Upchar Hospital",
"Veena Nursing Home",
"Veerayatan Netralaya",
"Vishnupur Nursing Home",
"Yogada Poly Clinic",
"Yugeshwar Kidney Hospital",
"Tara Nursing Home.",
"Shabnam Hospital",
"Manjhoul,Referal",
"Appolo Nursing Homeand Research Center",
"Bharat Nursing Home",
"Budha Hospital",
"Kuju Nursing Home",
"Maa Ambe Nursing Home",
"Matihani Referal",
"Nav Jeevan Hospital",
"Polo Hospital",
"Raj Nursing Home",
"Ram Krishna Hospitaland Medical Research Center",
"Rishi Sewa Sadan",
"Shyam Hospital",
"Susheela Hospital",
"Uday Nursing Home",
"Chand Suraj Hospital",
"Bishnupur Multi Speciality Hospital",
"Aashray Nursing Home",
"Angika Nursing Home",
"Annapurna Maternity Home",
"Anupam Nursing Home",
"Asraya Hospital",
"Dr Archana Jha Clinic and Nursing Home",
"Dr Suresh Pathology",
"Dr. Chandra Shekhar Shah",
"G.S. Hospital and Endolaparoscopy Centre",
"Gayatri Clinic and Maternity Centre",
"Healing Touch Centre",
"K K Nursing Home And Research Centre",
"Kaushalaya Eye Research Institute",
"Khageswari Nursing Home",
"Life Line Hospital",
"Loksewa Hospital",
"Orthopaedic Disease And Truma Care",
"Pushpdeep Trauma,Replacement And Spine Clinic",
"R K Heart and Helth Centre",
"Rakshit Nursing Home",
"Sahil Clinic",
"Saint Sharda Nursing Home",
"Sanjivani Nursing Home",
"Satyam Matri Shishu Kendra",
"Sharda Hospital",
"Shrishti Nursing Home",
"Sneh Nursing Home",
"Srijan Maternity and Fertility Clinic",
"Sushila Clinic",
"Tapashwi Hospital",
"Aastha Nursing Home and Maternity Centre",
"Aditya Nursing Home",
"Advance Maternity and Infertility Centre",
"Aziz Nursing Home",
"Jyoti Nursing Home",
"Khamriya Hospital",
"Lal Clinic",
"Shagun Nursing Home",
"Anumandaliya Hospital, Jagdishpur, Bhojpur",
"Ganinath Hospital",
"Heera Surya Nursing Home",
"Kanchan Shalya Niketan",
"Khwaja Garib Nawaz Welfare Society",
"Lilawati Nursing Home",
"Maa Jagdamba Nursing Home",
"Manav Kalyan Ewam Shodh Sansthan",
"Ortho Centre",
"Orthopaedics Clinic",
"Gloval Vishwamitra Hospital",
"Ma Shivratri Dental Health Hospital",
"Neha Nursing Home",
"Orthopadic Centre",
"R.R Memorial Hospital",
"Vishwamitra Hospital",
"Sadguru Nursing Home",
"Garib Nawaz Hospital",
"Marry Ward Health Centre",
"Rogi Kalyan Samiti,Sub.Divisional Hospital,Dumraon",
"Siddhashram Sewa Sadan",
"Darbhanga Medical College and Hospital",
"Aastha Hospital",
"Sheela Health Clinic",
"Shekhar Netralaya and Ear Nose Throat Hospital",
"Ugratara Hospital",
"Yashraj Surgical Sansthan",
"R B Memorial Hospital",
"Amrit Nursing Home",
"Anant Arogya Neketan ,",
"Arora Nursing Home",
"Dwivedi Clinic",
"Godawari Jiwachh Memorial Hospital",
"M/S Sanjay Surgical and Urological Kendra",
"M/S Sinha Clinic",
"Maa Bhagwati Nursing Home",
"Mahaseth Clinic",
"Matriva Nursing Home",
"Navjeevan Hospital",
"Nn Memorial Hospital",
"Prem Medical Research and Rehabilation Center (P) Ltd.",
"Prof. R.P.Gami Memorial Hospital",
"R.K. Ortho Ashram",
"R.R. Eye Hospital",
"Satya Sai Nursing Home",
"SubDivisional Hospital, Benipur",
"Agrachal Nursing Home",
"Chandra Shekhar Charitable Hospital",
"Godawari Jiwachh Hospital and Para Medical College",
"I B Smriti Arogya Sadan",
"Jyoti Research Hospital",
"M.S.Hospital",
"Mahamaya Nursing Home",
"R. S Memorial Hospital",
"Raj Gopal Health Care Centre",
"Sanjivani Hospital",
"Shyama Surgical Sansthan",
"Sri Ramjanki Arogya Niketan",
"Vidyshree Charitable Society",
"B. Smedical Centre",
"Singh Surgical Hospital",
"Maa Bhawani Nursing Home",
"Swasthya Kendra Khairwa",
"Aditya Arogya Sansthan",
"The Duncan Hospital",
"Sekhauna Swasthya Kendra",
"Aastha Nursing Home and Maternity Centre",
"Amar Clinic And Diabetic Care Centre",
"Astha Nursing Home",
"Banarsidas Chandiwala Eye Hospital",
"Bhawani Nursing Home",
"Chandana Surgicare",
"Dr. A. Rahmans Hospital",
"Hospito Care",
"Jai Shree Swasthya Kendra",
"Jeevan Deep Nursing Home",
"M.J. Heart Hospital",
"Maa Nursing Home",
"Maa Seva Sadan and Prasuti Kendra",
"Madan Raj Nursing Home",
"Madhuri Nursing Home",
"Maharaja Nursing Home",
"Motihari Medical Center",
"Om Sai Nursing Home",
"Rajpali Nursing Home",
"Shamima Health Center",
"Sharan Nursing Home",
"Shreyaskar Hospital",
"Surgicare",
"Susrut Shalya Chikitsha Kendra",
"Vatsalya Nursing Home",
"Yogendra Giri Sewa Ashram",
"Osho Healing Space",
"Referral Hospital",
"Chapra Endoscopy Academy And Centre For Minimally",
"Chandralekha Health Care",
"Matra Chaya",
"Sundaram Hospital",
"Jagannath Seva Sansthan(Medical Help Centre Ngo)",
"Sumitra Health Centre",
"Yuvraj Hospital",
"Shri Ganesh Seva Sadan",
"Ajeet Nursing Home",
"Sapna Nursing Home",
"Vaishanavi Hospital",
"Sehat Seva Kendra",
"A N Magadh Medical College and Hospital",
"Maa Bhawani Seva Sadan",
"Matri Sadan Nursing Home",
"Subham Nursing Home",
"Abhineet N H and Research Centre",
"Advanced Eye Care Centre",
"Agrawal Surgicalclinic and Hospital",
"Al-Zahir Navjeevan Hospital and Reasearch Center",
"Dr Prashant Nandkeolyar Nursing Home",
"Dr Vinod Kumar Singh",
"Dr. Asha Singhs Nursing Home",
"Gautam Patho Lab",
"Get - Well Hospital and Research Centre",
"Haddy Hospital and Art Center",
"Health Touch Hospital",
"Jeevan Rekha Dia and Nursing Home",
"Jindal Hospital and Endosurgery Center",
"Kaushalya Nursing Home",
"Mateshwari Nursing Home",
"Nav Jeewan Nursing Home",
"Ortho Center",
"Satyam Nursing Home",
"Asha Nursing Home",
"Ashirbad Nursing Home",
"Radhika Sewa Sadan",
"Sanjevani Nursing Home",
"Sri Krishna Nursing Home and Maternity Center",
"Satyam Hospital",
"Hind Nursing Home and Anusandhan Kendra.",
"Dr. Jagdish Prasad Memorial Hospital.",
"Rog Nidan Charitable Hospital",
"Dr. Kundu Poly Clinic",
"Nidaan Kendra",
"Rishav Nursing Home",
"Ashutosh Nursing Home",
"Bharat Nursing Home.",
"Buddha Nursing Home.",
"Maa Mangla Sewa Sadan",
"Maa Shaarde Sewa Sadan",
"Prajapati Sewa Ashram",
"Raj Kamal Nursing Home.",
"Surgical Nursing Home and Maternity Center.",
"Gayatri Sewa Sadan",
"Tekari Nursing Home",
"Maharani Jagroshna Devi Hospital and Maternity Home",
"Biprasi Hospital",
"Dr. Subhash Chandra Gupta",
"Jagdamba Nursing Home",
"Medical Institute and Hospital (Dr. M. Kumar)",
"Nayan Sukh Netralay",
"Saurav Hospital",
"Surgi Uro Centre",
"Upkar Seva Sadan",
"Alam Hospital",
"Sanjivani Hospital",
"Aditya Seva Sadan",
"Deo Pushpa Computerised Orthopedic And Maternity C",
"Dr Amit Anand-Hospital",
"Dr Pankaj Kumar",
"Dr Rajesh Kumar",
"Dr. Manju (Chauhan) Kumari",
"Godawari Clinic",
"Hi-Tech Clinic",
"Maa Jagdamba Clinic",
"Swami Vivekanand Hospital",
"Anamika Memorial Hospital",
"Hussain Nursing Home",
"Jeevandeep Nursing Home and Maternity Centre",
"Neha Nursing Home",
"Sushila Nursing Home",
"Swasdhya and Parivar Kalyan Vibhag Hospital",
"Referal Hospital Makhdumpur",
"Raj Public Welfare Hospital",
"Gandhi Kusth Nivaran Pratisthan",
"Ranjan Hospital",
"Srijan Hospital",
"Prakash Hospital",
"Dr.Awinash Clinic",
"Dr.Bhrigunath Singh Memorial Hospital",
"Dr.Parashnath Hospital",
"Mansarover Hospital",
"Sanjeevani Hospital",
"Apolo Charitable Hospital",
"Kushi Health Care Centre",
"Maa Shardha Child and Adult Health Care Centre",
"Pooja Nursing Home",
"S.B.Nursing Home",
"Ujjwal Nursing Home",
"Onyx Dental And Implant Center",
"Sanjeewini Nursing Home",
"Satyabhama Netralaya",
"Advanced Bone Center",
"Biswas Health Clinic",
"Chaturbhuj Surgicare",
"Devesh Nursing Home",
"Dr Arif Clinic",
"Dr. M M Haque Nursing Home",
"Godawari Dinanath Matri Evam Shishu Kalyan Niketan",
"Jannakshya Nursing Home",
"K K Matri Seva Sadan",
"Katihar Seva Sadan",
"Lodi Health Clinic",
"Manish Nursing Home",
"Minat Nursing Home",
"Nidaan Hospital",
"Nirog Nursing Home",
"Patna Hospital",
"Popular Sewa Sadan",
"Shamim Nursing Home",
"Sharan Clinic",
"Sheefa Health Clinic",
"Sub Div Hospital Manihari",
"Y F A Hospital and Research Centre",
"Foundation Life For All",
"Rubeda Nursing Home",
"Shaheed Prabhu Narayan Multispeciality Hospital",
"Swastim Hospital And Stone Clinic",
"Mgm Medical College",
"Divya Haddi Aur Daat Hosp",
"Haider Nursing Home",
"Jai Tulsi Nursing Home",
"K.B Nursing Home",
"Kanchanlata Nursing Home",
"Khwaja Garib Nawaz",
"Life Care Nursing Home",
"Maa Janaki Nursing Home",
"Madhab Surgical and Maternity Clinic",
"N B Nursing Home",
"Rabia Nursing Home",
"Shaukat Nursing Home",
"Smile Dental Clinic",
"Z.A.Nursing Home",
"Ab Nursing Home",
"Bhairon Bhakt Raghunath Rai Netralaya",
"Hussain Memorial Nursing Home",
"Chitranjan Sevasadan General",
"Dr Chandra Mohan Prasad",
"Dr Naresh Mandal",
"Dr Ramanuj",
"Maa Tara Haddi Avam Nas Jod Hospital",
"Muskan Nursing Home",
"Netralok Hospital",
"S S Hospital",
"Shiv Shakti Seva Sadan",
"Shree Krishna Sewa Sadan",
"Shri Ashokdham General And Surgical Hospital",
"Aditya Arogya Sansthan",
"Care Nursing Home",
"Druvit Hospital",
"Madhipura Christian Hospital Society",
"Pradhi Yadav Hospital",
"Pragyan Nursing Home",
"Satish Memorial Hospital And Research Center",
"Vinit Nursing Home",
"Vrindavan Nursing Home",
"Ramkrishana Hospital and Medical Research Centre-Madhepura",
"Dr.D K Gupta",
"Heart Hospital",
"Heritage Hospital and S N R L Trauma and Orthopedic R",
"Jeeva Deep Charitable Trust",
"Golu and Lucky Medicare Home",
"Astha Hospital",
"Balajee Hospital",
"Sardaun Memorial Arogya Clinic",
"Dr. Uma Kant Jha",
"Dr. Ak Singh Clinic",
"Siddhi Saakshi Swasthya Sewa Sadan",
"Veena Diagnostic and Research Hopsital",
"Z K Memorial Hospital",
"Dinesh Nursing Home",
"Haider Hospital and Reasearch Center",
"Jeevan Jyoti Nursing Home",
"Mithilanchal Nursing Home",
"Nayan Jyoti Netralaya",
"Surgical Clinic",
"Sub-Divisional Hospital, Jhanjharpur (Madhubani)",
"Arpan Ortho Hospital",
"Bhagwan Gautam Buddha Hospital",
"Dr. J. K. Barma Memorial Medicare and Reaserch Centre",
"Gomati Goenka Matri Sadan",
"Jeevan Avtar Hospital",
"Jeevan-Jyoti Medical and Research Center-Munger",
"Life Line Nursing Home",
"Manju Poly Clinic",
"Modern Eye Centre",
"Munger Surgery",
"Nivedita Suirgicle Care and Research Centre",
"Om Hospital",
"Pushkal Medicare and Research Centre",
"Raj Hospital And Research Centre",
"Raj Kumari Nursing Home",
"Raksha Deep Ortho Research Centre",
"Sahay Nursing Home",
"Samarpan Hospital And Research Centre",
"Sevayan Medical And Research Centre - Munger",
"Surims and Hospital",
"Urmila Nursing Home",
"Sri Krishna Memorial College and Hospital",
"Apollo Maternity",
"Ayushman Nursing Home",
"B.M.Thakur Clinic",
"Bhawani Hospital",
"Dr. Brajesh Kumar Ortho and Trauma Care",
"Help Clinic",
"Indra Sewa Sadan",
"Jivan Deep Clinic",
"Kailash Nursing Home",
"Krishnadevi Deviprasad Kejriwal Maternity Hospital",
"Maa Janki Hospital and Research Center Pvt Ltd",
"Mishra Hospital",
"Modern Nurshing Home",
"Muzaffarpur Heart Hospital and Research Centre Pvt. Ltd.",
"Netralaya",
"Om Nursing Home and Maternity Centre",
"Parijat Nursing Home",
"Pragya Sewa Sansthan",
"Prashant Memorial Charitable Hospital",
"R N M Hospital",
"R.P.M.C.Hospital",
"Sadar Hospital Muzaffarpur.(Bihar)",
"Sanjeevani Clinic and Nursing Home",
"Shahjahan Memorial Hospital",
"Sight Care",
"Standard Diagnostics",
"Aseem Healthcare and Trauma Centre",
"Ayush Hospital",
"Healthy Home",
"Leelawati Hospital",
"Maa Tara Sewa Sadan",
"Roy Nursing Home and Maternity Centre",
"Amal Nursing Home",
"Bathua Nursing Home",
"Care Nursing Home",
"Dr. R.N. Thakur Memorial Clinic",
"Shri Krishna Medical College And Hospital",
"Jeevan Rekha Arogya Sansthn",
"Super Hospital",
"Mehta Seva Sadan",
"Kabirayatan Eye Hospital and Research Institute",
"Sharda Laxmi Surgery Centre",
"Dr. B.R. Ambedkar Hospital and Research Centre",
"Jivan Jyoti Nursing Home",
"Sandali Hospital Pvt. Ltd.",
"Gokul Pariwar and Shishu Swasthya Kendra",
"Nath Nursing Home",
"Shiv Nursing Home",
"Aastha Hospital",
"Apollo Surgical Center",
"Ashirbad Sewa Sanstha",
"Bihar Clinic",
"Delhi Hospital",
"Dr Ashwani Ent Hospital",
"Dr. Maj.Sanjay Kumar",
"Harihar Hospital",
"Jahnavi Eye Care and Research Center",
"Janani Clinic",
"Janki Aarogyam",
"Jaya Nursing Home",
"Jeevan Jyoti Hospital",
"Khushboo Hospital",
"Kisan Nursing Home and Hospital Pvt Ltd",
"Mamta Mother and Child Hospital(P)Ltd.",
"Nalanda Netralaya and Maternity Home Pvt. Ltd.",
"Opolo Surgical and Urology Centre",
"Orthocare",
"Prasad Nethralaya and Surgical Centre",
"Prashant Nursing Home",
"Sanjivani Hospital",
"Satyam Nursing Home",
"Sharwan Poly Clinic",
"Sms Nursing Home",
"Suhagi Clinic",
"Surya Nursing Home",
"Tara Aarogya Sasthan",
"Vijeta Nursing Home",
"Voluntary Hospital",
"Sri Ram Govind Pyare Hospital",
"Janta Nursing Home",
"Netra Jyoti Seva Mandiram",
"Sri Mahavir Arogya Sewa Sansthan and Research Institute",
"Gautam Budha Hospital and Research Institute Private Limited",
"Matritva Chhaya Hospital",
"Akhand Jyoti Eye Hospital",
"Magadh Hospital and Research Centre",
"Muskan Hospital",
"Aadarsh Nursing Home",
"Aarya Swashthya Seva Sansthan",
"City Hospital",
"Dr.Ganga Rani Memorial Hospital",
"G.S.K.Memorial Clinic",
"Jankalyan Seva Sadan",
"Kamala Nursing Home",
"Life Line Nursing Home",
"Maa Laxmi Clinic",
"Magadh Institute Of Para Medical Science",
"Milky Awamulnas Sewa Santhan",
"Surgical Centre",
"Swasthya and Parivar Kalyan Vibhag",
"Tathagat Hospital",
"Vivek Nursing Home",
"Maa Tara Hospital and Research Centre",
"Yadav Health Clinic",
"All India Institute of Medical Sciences (AIIMS), Patna",
"Patna Medical College and Hospital",
"Nalanda Medical College and Hospital",
"Indira Gandhi Institute of Medical Sciences",
"Rajendra Memorial Research Institute of Medical Sciences",
"Paras HMRI Hospital",
"Ford Hospital",
"Kurji Holy Family Hospital",
"Rajeshwar Hospital",
"Jagdish Memorial Hospital",
"Sahyog Hospital",
"Dr.Ruban Memorial Hospital",
"Dr. Bimal Hospital and Research Center",
"Ishwar Dayal Memorial Hospital",
"Magadh Hospital",
"Arvind Hospital",
"Advanced Eye Care",
"Advanced Neuro Diagnostic Centre",
"Akshat Seva Sadan",
"Anami Orthopaedics",
"Brindavan Nursing Home",
"Chand Memorial Hospital",
"Chaupal Hospital Pvt Ltd",
"Chikitsa Nursing Home",
"Child Hospital",
"Childrens Hospital",
"Cns Sanjeevani Centre For Neurosurgery Pvt Ltd",
"D N Singh Memorial Trust",
"Dr Ruban Memorial Hospital And Ratan Stone Clinic",
"Dr. Sarojini Sinha Memorial Shiv-Shakti Hospital",
"Hai Medicare and Research Institute",
"Harsh Clinic",
"Jeevak Shalya Nilayam",
"Jyoti Punj Hospital",
"K. B. Surgical Clinic",
"Keshav Hospital Pvt Ltd",
"L.B.Aparajita Hospital",
"Laxmi Nursing Home Pvt. Ltd",
"Mahavir Vaatsalya Aspatal",
"Manav Orthopaedic Clinic And Maternity Home",
"Max Care Hospital And Research Institute Pvt. Ltd.",
"Neeti Nursing Home",
"Ortho Care Centre and Nursing Home",
"Orthopadic Center",
"P.K.Nursing Home Awam Maternity Centre",
"Patliputra Netradham Eye Hospital",
"Sanjeevani Eye Hospital and Research Institute",
"Sheila Urology Centre",
"Sparsh Haritage Hospital",
"Tara Hospital and Medical Research Centre Pvt Ltd",
"Abhinav Clinic",
"Arvind Diabetic Critical Care Hospital",
"Indira Nursing Home",
"Neetumedicare Nursing Home",
"Pataliputra Nursing Home",
"R.M.Hospital and Research Centre",
"Ranjana Singh Nursing Home",
"Saraswati Hospital and Reseaarch Centre",
"Aarogya Orthopaedic and Trauma Clinic",
"Bilas Netralaya",
"M.G.M Hospital And Research Centre Pvt Ltd",
"Priya Clinic",
"Anupama Hospital Pvt. Ltd.",
"Arvind Hospital Pvt. Ltd.",
"Buddha Nursing Home",
"E N T Hospital and Research Centre",
"Hii Tech Emergency Hospital",
"Kumar Eye Centre",
"Kumar Nursing Home",
"Om Nursing Home",
"Pandey Nursing Home",
"Patna Medical Collage and Hospital",
"Popular Nursing Home",
"Shyam Nursing Home",
"Siddiqui Nursing Home and M.R.C. Pvt. Ltd.",
"Sri Vinayak Hospital",
"Imdad Medicare Research Institute",
"Ram Ratan Hospital",
"Aditya Hospital",
"Akriti Nursing Home",
"Apex Hospital",
"Bhartiya Arogyas Sansthan",
"Magadh Nursing Home",
"Polo Hospital",
"Pragya Nursing Home",
"Pramila Nursing Home",
"Raj Lakshmi Chikitsa Kendra",
"Sanjivani Nursing Home",
"Susruta Surgical Clinic",
"Tripolia Social Service Hospital",
"A.S.Nursing Home",
"Hindustan Poly Clinic",
"Manokamna Health Care",
"Pal E.N.T. Clinic and Research Centre",
"R.P. Golwara Memorial Hospital",
"The Birth Maternity Home",
"Kurji Holy Family Hospital",
"Advance Ortho Care Centre",
"Narain Nursing Home",
"Renu Eye Center",
"Renuka Orthopaedic Hospital",
"Sahyog Hospital",
"Shah Maternity Clinic",
"Shekhar Hospital",
"Agrawal Maternity Centre",
"Ambika Memorial Trust",
"Ashiana Nursing Home(Pvt) Ltd",
"City Hospital - Patna",
"Divya Drishti Eye Centre",
"Divya Jyoti Nursing Home",
"Dr. Bimal Hospital And Researhc Centre Pvt Ltd",
"Getwell Hospital",
"Indira Gandhi Istitute Of Medical Science Sheikhpu",
"Krishna Health Care",
"Punam Surgical and Maternity Clinic",
"R N Superspecility Hospital And Research Centre",
"Ramwati Nursing Home",
"Satyam Nursing Home and Research Centre (P) Ltd",
"Shyamal Hospital",
"Urology Center",
"Vimal Hospital and Research Centre",
"A K Nursing Home",
"A.B. Eye Institute",
"Ambe Nursing Home",
"Antar Jyoti Charitable Eye Hospital",
"Ashoka Hospital( Aunit Of Ashoka Multispeciality Hospital Pvt Limited)",
"Bharti Nursing Home",
"Chakore Nursing Home",
"Dr. Nirmala Rai",
"Dr. Subhas Chandra Chaudhary Clinic",
"Dr. Usha Didwania Nursing Home",
"Institute Of Orthopaedic Research and Fracture Surge",
"Laxman Care Centre",
"Magadh Hospital",
"Mma Hospital and Research Centre",
"Mother Care Maternity Centre",
"New Born Care Centre (P) Ltd",
"Pulse Icu and Trauma Centre",
"Shahi Hospital (A Unit Of Abhishek Memorial Trust)",
"Shanti Maternity Centre",
"Shiv Nav Jyoti Hospital",
"Shiv Shishu Hospital",
"Siddharth Multispeciality Hospital",
"Syamala Clinic and Maternity Research Centre",
"Sri Hari Jeevan Health Care",
"Abhinandan Hospital",
"Anand Hospital",
"Anup Memorial Orthopaedic Centre",
"Apollo Trauma Centre",
"Appolo Burns Hospital",
"Buddha Eye Care and Laser Centre",
"Chanakya Hospital",
"Chandra Shambhu Narayan Eye Hospital Pvt. Ltd.",
"Child Care Center",
"Choupal Hospital Pvt Ltd",
"Clinic and Maternity Centre",
"Drishti Eye Care And Research Centre",
"Dubey Urology Clinic and Stone Centre",
"Eye Foundation",
"Ford Hospital and Research Centre Pvt Ltd",
"Gayatri Nursing Home and Maternity Centre",
"Harsh Hospital - Patna",
"Heart Hospital",
"Hope Child Care and Research Centre",
"Hope Pharma",
"Ishwar Dayal Hospitals Pvt Ltd",
"J.H.Nursing Home",
"Jagdish Memorial Hospital",
"Janaki Hospital and Maternity Center",
"Jeevak Heart Hospital and Research Institute Pvt Ltd",
"K D Hospital",
"Kalawind Adarsh Hospital",
"Khushi Hospital",
"Kiran Nursing Home",
"Krishna City Hospital",
"Krishna Nursing Home",
"Kumar Clinic",
"Laxmi Nursing Home",
"Life Line Hospital",
"Magalam Hospital",
"Mahavir Arogya Sansthan",
"Manas Nursing Home",
"Manglam Hospital",
"Matrichhaya Ortho and Health Care",
"Megha Hospital",
"Metro Trauma Hospital",
"Mithila Hospital",
"Nav Sharda Aspatal Pvt Ltd",
"New Kumar Nursing Home",
"Om Eye Clinic and Phaco Centre - Patna",
"Patliputra Divine Hospital Pvt Ltd",
"Patna Bone And Spine Hospital Pvt Ltd",
"Perfect Nursing Home",
"Prakash Hospital",
"Rajeshwar Hospital",
"Ramkrishna Welfare Hospital",
"Ruban Emergency Hospital",
"S. R. Hospital",
"S.S.Hospital and Research Centre Pvt.Ltd.",
"Sankalp Heart Center",
"Saroj Mother and Child Care Centre",
"Shanti Navjeevan Hospital Pvt. Ltd.",
"Shekhar Shalya Chikitsalaya",
"Shivam Hospital And Research Institute Pvt Ltd",
"Shri Ram Hospital",
"Shri Sai Hospital (A Unit Of Akhilesh Kumar Singh Hospital (P)Ltd)",
"Shrinivas Hospital - Patna",
"Shubham Maternity Centre",
"Sri Jagannath Sewa Sadan",
"Sri Ram Hospital and Research Centre",
"Sri Sai Lions Netralaya",
"Srijan Centre For Assisted Human Reproduction",
"Suman Nursing Home",
"Sundari Devi Hospital",
"Swasti Womens Hospital And Research Centre",
"The Apollo Clinic",
"Uma Foundation",
"Vijai Hospital",
"Dr S M Hospital and Research Centre",
"Dr.Rupam Sinha Clinic",
"Jagdamba Nursing Home",
"Shivam Chikisalya Kendra",
"Specialist Clinic and Nursing Home",
"I Care Eye Hospital and Research Centre",
"Sarvamangla Clinic",
"Shree Ishwar Dayal Hospital",
"Vaishnavi Hospital",
"Maa Dulari Memorial Hospital",
"Aarogya Hospital",
"New Kumar Nursing Home",
"Ekram Nursing Home",
"Lord Buddha Research Hospital",
"Ashutosh Memorial Hospital",
"Atlantis Hospital",
"Anshuman Nursing Home and Maternity Centre",
"Kb Hospital and Research Institute - Patna",
"Life Care Maternity Home,",
"Mahavir Cancer Sansthan",
"Maulana Sajjad Memorial Hospital",
"S. M. Life Care Hospital",
"Sahaj Surgery",
"Sanjeevani Nursing Home",
"Hari Swasthya Sahayog Kendra",
"Sri Durga Arogya Niketan",
"Central Hospital",
"Shri Jai Govind Hospital and Research Centre",
"Dev Nursing Home",
"Janta Poly Clinic",
"Pushpa Hospital",
"Maa Brahmani",

  ];

  List<String> displayedItems = [];

  @override
  void initState() {
    super.initState();
    // Initialize displayedItems with all items initially
    displayedItems.addAll(allItems);
  }

  void _filterSearchResults(String query) {
    List<String> searchResults = [];

    if (query.isNotEmpty) {
      for (String item in allItems) {
        if (item.toLowerCase().contains(query.toLowerCase())) {
          searchResults.add(item);
        }
      }
    } else {
      // If the query is empty, display all items
      searchResults.addAll(allItems);
    }

    setState(() {
      displayedItems.clear();
      displayedItems.addAll(searchResults);
    });
  }

  @override
  Widget build(BuildContext context) {
    Future<void> _launchURL(String url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
    return Scaffold(
      body: Stack(
        children: [
          Container(
            decoration: const BoxDecoration(
              image: DecorationImage(
                image: AssetImage(
                    'assets/nurse.jpg'), // Replace with your image path
                fit: BoxFit.cover,
              ),
            ),
          ),
          Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: TextField(
                  controller: _searchController,
                  onChanged: _filterSearchResults,
                  decoration: InputDecoration(
                    filled: true,
                    fillColor: const Color.fromARGB(255, 173, 227, 251),
                    labelText: 'Search',
                    hintText: 'Search...',
                    prefixIcon: const Icon(Icons.search),
                    border: const OutlineInputBorder(
                      borderRadius: BorderRadius.all(
                        Radius.circular(10.0),
                      ),
                    ),
                  ),
                ),
              ),
              Expanded(
                child: ListView.builder(
                  itemCount: displayedItems.length,
                  itemBuilder: (context, index) {
                    return Card(
                      child: ListTile(
                        title: Text(displayedItems[index]),
                        trailing: IconButton(icon: Icon(Icons.search),onPressed: () {
                          _launchURL('https://www.google.com/search?q=${displayedItems[index]}');
                        },),
                        leading:IconButton(icon: Icon(Icons.map),onPressed: () {
                          _launchURL('https://www.google.com/maps/dir/kochi/${displayedItems[index]}/');
                        },), 
                        // Add more card content as needed
                      ),
                    );
                  },
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
